### ISSUE TITLE
pnpm install failure on macOS

### ISSUE THREAD

**Issue by thclark** [unfoldadmin/turbo#1]
(what's the point of dockerizing amiright?!!)

Great work on this demo, thank you, it shows nicely how the two interact!!

For other users, I get the following error:
```
ERR_PNPM_LINKING_FAILED  Error: ENOENT: no such file or directory, copyfile '/app/.pnpm-store/v3/files/46/a8b19d0de0d23c31939e2fcfb51a6db0b0fc8159612f3583bdd9bed982472e0f9aa8e9b245aef92216eb784efae03921fafec140e621430ccb28c02d966cf3' -> '/app/node_modules/.pnpm/es-abstract@1.22.1/node_modules/es-abstract_tmp_9/2021/ArraySetLength.js'
```

[I believe this is the offending issue](https://github.com/pnpm/pnpm/issues/7024).

To solve it I did:
```
echo "package-import-method=clone-or-copy" > frontend/.npmrc
```

Hope this helps someone!

**Comment by lukasvinclav** [comment]
I just tested the app and I was not able to reproduce this issue. Do you have this problem when you are running "docker-compose up"?

**Comment by tricelex** [comment]
I also came across this issue while running via docker on MacOS, I solved it by changing Docker settings from VirtioFS to gRPC FUSE

**Comment by lukasvinclav** [comment]
fixed
