### ISSUE TITLE
Getting an error while creating account

### ISSUE THREAD

**Issue by artp1ay** [unfoldadmin/turbo#15]
<img width="987" alt="error" src="https://github.com/user-attachments/assets/6d1a4b8e-6eeb-48e2-9f05-24fdbfcb4636">

Trying to signup, getting an error message, account was not created.

Log
```
web-1  |  POST /register 200 in 38ms
web-1  |  GET /api/auth/providers 200 in 14ms
web-1  |  GET /api/auth/signin?callbackUrl=http%3A%2F%2Flocalhost%3A3100%2Fregister 302 in 8ms
web-1  |  GET /login?callbackUrl=http%3A%2F%2Flocalhost%3A3100%2Fregister 200 in 29ms
api-1  | [08/Aug/2024 13:52:23] "POST /api/users/ HTTP/1.1" 201 24
web-1  |  GET /api/auth/session 200 in 29ms
web-1  |  GET /api/auth/session 200 in 21ms
```

**Comment by lukasvinclav** [comment]
I just tested this functionality with the current `main` and it works as expected. Are you sure that you din't changed any code? Would you mind to try to rebuild the containers?
