### ISSUE TITLE
README.md - Update Docker Compose Instructions for macOS

### ISSUE THREAD

**Issue by dottenbr** [unfoldadmin/turbo#16]
When running `docker-compose up` on macOS with Docker Desktop installed, users may encounter the error `zsh: command not found: docker-compose`. Starting from Docker Desktop version 3.3, Docker Compose has been integrated into Docker itself, and the command has changed to `docker compose` (without the hyphen).

To avoid confusion, the README.md should be updated to reflect the correct usage of Docker Compose in newer versions of Docker Desktop. The updated command should be: `docker compose up`.

**Comment by lukasvinclav** [comment]
Thanks for report. PR fixing issue #17
