### ISSUE TITLE
can the backend API (django-rest-framework) part be replaced with django-ninja?

### ISSUE THREAD

**Issue by Deali-Axy** [unfoldadmin/turbo#29]
This is a very good scaffolding for a django project, can the backend API (django-rest-framework) part be replaced with django-ninja? Compared to django-rest-framework, ninja development is more flexible and has a smoother learning curve.

I'm actually developing a similar scaffolding for django projects (called DjangoStarter) and switched from django-rest-framework to django-ninja in a recent new release and it feels great!

**Comment by lukasvinclav** [comment]
I don't have any experience with django-ninja but if you want to replace django-rest-framework, feel free to do that.
