### ISSUE TITLE
error while registering

### ISSUE THREAD

**Issue by rishigupta87** [unfoldadmin/turbo#9]
I am getting connection error when trying to signup, everything is set up right, any idea?

eb_1  | TypeError: fetch failed
web_1  |     at node:internal/deps/undici/undici:12344:11
web_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web_1  |   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
web_1  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
web_1  |       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
web_1  |     errno: -111,
web_1  |     code: 'ECONNREFUSED',
web_1  |     syscall: 'connect',
web_1  |     address: '127.0.0.1',
web_1  |     port: 8000
web_1  |   }
web_1  | }
web_1  | TypeError: fetch failed
web_1  |     at node:internal/deps/undici/undici:12344:11
web_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web_1  |   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
web_1  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
web_1  |       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
web_1  |     errno: -111,
web_1  |     code: 'ECONNREFUSED',
web_1  |     syscall: 'connect',
web_1  |     address: '127.0.0.1',
web_1  |     port: 8000
web_1  |   }
web_1  | }
web_1  |  ⨯ unhandledRejection: TypeError: fetch failed
web_1  |     at node:internal/deps/undici/undici:12344:11
web_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web_1  |   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
web_1  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
web_1  |       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
web_1  |     errno: -111,
web_1  |     code: 'ECONNREFUSED',
web_1  |     syscall: 'connect',
web_1  |     address: '127.0.0.1',
web_1  |     port: 8000
web_1  |   }
web_1  | }
web_1  |  ⨯ unhandledRejection: TypeError: fetch failed
web_1  |     at node:internal/deps/undici/undici:12344:11
web_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web_1  |   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
web_1  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
web_1  |       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
web_1  |     errno: -111,
web_1  |     code: 'ECONNREFUSED',
web_1  |     syscall: 'connect',
web_1  |     address: '127.0.0.1',
web_1  |     port: 8000
web_1  |   }
web_1  | }

**Comment by lukasvinclav** [comment]
I just updated dependecies and did some testing. Everything seems to work as expected. In case you have still the same error please reopen the issue.
